spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: maindb
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/migration
    username: postgres
    password: postgres
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #optional - enable SQL statements formatting.
#       format_sql: true

  batch:
    job:
      enabled: false
    jdbc:
#      switch to never if using not temp database https://runebook.dev/en/docs/spring_boot/application-properties/application-properties.integration.spring.batch.jdbc.schema
      initialize-schema: always
#     reset batch job tables for each app start
      schema: classpath:/db/target/schema-postgresql.sql

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  cache:
    type: jcache
#  main:
#    allow-bean-definition-overriding: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
      root: debug
      org.springframework.boot.autoconfigure.mongo.embedded: error
      Batch: INFO
      ru.otus.hw: INFO

  file:
    name: hw.log


