---
apiVersion: v1
kind: ConfigMap
metadata:
  name: library-service-config
data:
  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=80 -XX:MaxRAMPercentage=80
  SPRING_DATASOURCE_URL: jdbc:h2:mem:maindb
  SPRING_DATASOURCE_USERNAME: sa