---
apiVersion: v1
kind: Service
metadata:
  name: library-entrypoint
  # namespace: default
  labels:
    app: library
spec:
  selector:
    app: library
  ports:
    - port: 8181
      targetPort: 8080
      name: app-main
    - port: 8191
      targetPort: 8090
      name: app-actuator
  type: NodePort
